/* Generated By:JavaCC: Do not edit this line. BattlelandRandomizerLoaderConstants.java */
package net.sf.colossus.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BattlelandRandomizerLoaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 4;
  /** RegularExpression Id. */
  int NOTNEWLINE = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int AREA = 7;
  /** RegularExpression Id. */
  int HAZARDS = 8;
  /** RegularExpression Id. */
  int KEYLABEL = 9;
  /** RegularExpression Id. */
  int SOMEOF = 10;
  /** RegularExpression Id. */
  int SUBSTRACT = 11;
  /** RegularExpression Id. */
  int SURROUNDINGSOF = 12;
  /** RegularExpression Id. */
  int PAIR = 13;
  /** RegularExpression Id. */
  int HEXSIDES = 14;
  /** RegularExpression Id. */
  int LEFTOVER = 15;
  /** RegularExpression Id. */
  int USEDUP = 16;
  /** RegularExpression Id. */
  int STARTLIST = 17;
  /** RegularExpression Id. */
  int TOWER = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int FPNUMBER = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int OPENPAR = 24;
  /** RegularExpression Id. */
  int CLOSEPAR = 25;
  /** RegularExpression Id. */
  int CARET = 26;
  /** RegularExpression Id. */
  int EQUAL = 27;
  /** RegularExpression Id. */
  int STAR = 28;
  /** RegularExpression Id. */
  int CASELABEL = 29;
  /** RegularExpression Id. */
  int HAZARD = 30;
  /** RegularExpression Id. */
  int CHAINE = 31;
  /** RegularExpression Id. */
  int QUOTEDCHAINE = 32;
  /** RegularExpression Id. */
  int CAR = 33;
  /** RegularExpression Id. */
  int NUMCAR = 34;
  /** RegularExpression Id. */
  int QUOTEDCAR = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMMENT>",
    "<NOTNEWLINE>",
    "\"\\n\"",
    "\"AREA\"",
    "\"HAZARDS\"",
    "\"LABEL\"",
    "\"SOMEOF\"",
    "\"SUBSTRACT\"",
    "\"SURROUNDINGSOF\"",
    "\"PAIR\"",
    "\"HEXSIDES\"",
    "\"leftover\"",
    "\"usedup\"",
    "\"STARTLIST\"",
    "\"TOWER\"",
    "<NUMBER>",
    "<FPNUMBER>",
    "<DIGIT>",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"=\"",
    "\"*\"",
    "<CASELABEL>",
    "<HAZARD>",
    "<CHAINE>",
    "<QUOTEDCHAINE>",
    "<CAR>",
    "<NUMCAR>",
    "<QUOTEDCAR>",
  };

}
