# Makefile for Colossus
# dripton  June 26, 1998
# Make sure to save this file in Unix rather than DOS endline format, so that
#    it will continue to work portably.


JC = jikes -depend -g -deprecation
#JC = javac -depend -J-Djavac.pipe.output=true -g -deprecation
#JC = javac -depend -J-Djavac.pipe.output=true -O:interclass


all: BattleMap.class \
     BattleChit.class \
     BattleTurn.class \
     Chit.class \
     Concede.class \
     Creature.class \
     Game.class \
     Hex.class \
     Legion.class \
     MasterBoard.class \
     MasterHex.class \
     Negotiate.class \
     PickEntrySide.class \
     PickMarker.class \
     PickRecruit.class \
     Player.class \
     ShowLegion.class \
     SplitLegion.class \
     SummonAngel.class \
     Turn.class

BattleMap.class: BattleMap.java
	$(JC) BattleMap.java

BattleChit.class: BattleChit.java
	$(JC) BattleChit.java

BattleTurn.class: BattleTurn.java
	$(JC) BattleTurn.java

Chit.class: Chit.java
	$(JC) Chit.java

Concede.class: Concede.java
	$(JC) Concede.java

Creature.class: Creature.java
	$(JC) Creature.java

Game.class: Game.java
	$(JC) Game.java

Hex.class: Hex.java
	$(JC) Hex.java

Legion.class: Legion.java
	$(JC) Legion.java

MasterBoard.class: MasterBoard.java
	$(JC) MasterBoard.java

MasterHex.class: MasterHex.java
	$(JC) MasterHex.java

Negotiate.class: Negotiate.java
	$(JC) Negotiate.java

PickEntrySide.class: PickEntrySide.java
	$(JC) PickEntrySide.java

PickMarker.class: PickMarker.java
	$(JC) PickMarker.java

PickRecruit.class: PickRecruit.java
	$(JC) PickRecruit.java

Player.class: Player.java
	$(JC) Player.java

ShowLegion.class: ShowLegion.java
	$(JC) ShowLegion.java

SplitLegion.class: SplitLegion.java
	$(JC) SplitLegion.java

SummonAngel.class: SummonAngel.java
	$(JC) SummonAngel.java

Turn.class: Turn.java
	$(JC) Turn.java

