/* Generated By:JavaCC: Do not edit this line. StrategicMapLoaderConstants.java */
public interface StrategicMapLoaderConstants {

  int EOF = 0;
  int EOL = 4;
  int CASE = 5;
  int NUMBER = 6;
  int DIGIT = 7;
  int TERRAIN = 8;
  int WAY = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"CASE\"",
    "<NUMBER>",
    "<DIGIT>",
    "<TERRAIN>",
    "<WAY>",
  };

}
