#!/bin/sh
# Run 6-AI games in a loop forever, looking for hangs.
# XXX The log will eventually fill the disk. 
while true; 
    do ./run -i 6 -q -g -d 1 $1 $2 $3 $4 $5 $6 $7 $8 $9 >> log 2>> log;
done
