/* Generated By:JavaCC: Do not edit this line. TerrainRecruitLoaderConstants.java */
public interface TerrainRecruitLoaderConstants {

  int EOF = 0;
  int EOL = 4;
  int NUMBER = 5;
  int DIGIT = 6;
  int TERCAR = 7;
  int CHAINE = 8;
  int CAR = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGIT>",
    "<TERCAR>",
    "<CHAINE>",
    "<CAR>",
  };

}
