/* Generated By:JavaCC: Do not edit this line. VariantLoaderConstants.java */
public interface VariantLoaderConstants {

  int EOF = 0;
  int EOL = 4;
  int CHAINE = 5;
  int CAR = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CHAINE>",
    "<CAR>",
    "\"MAP:\"",
    "\"CRE:\"",
    "\"TER:\"",
  };

}
