package net.sf.colossus.client;

import java.util.*;
import junit.framework.*;

import net.sf.colossus.server.Creature;
import net.sf.colossus.server.Game;
import net.sf.colossus.server.VariantSupport;
import net.sf.colossus.util.Log;


/**
 *  JUnit test for split prediction.
 *  @version $Id$
 *  @author David Ripton
 */
public class PredictSplitsTest extends TestCase
{
    List cnl;
    AllPredictSplits aps;
    PredictSplits ps;
    int turn = 0;


    public PredictSplitsTest(String name)
    {
        super(name);
    }

    protected void setUp()
    {
        VariantSupport.loadVariant("Default", true);
        aps = new AllPredictSplits();

        cnl = new ArrayList();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Ogre");
        cnl.add("Ogre");
    }


    public void testPredictSplits1()
    {
        ps = new PredictSplits("Red", "Rd01", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        Node root = ps.getLeaf("Rd01");
        assertTrue(root != null);
        assertTrue(ps.getLeaves(root) != null);
        ps.getLeaf("Rd01").split(4, "Rd02", turn);
        ps.getLeaf("Rd01").merge(ps.getLeaf("Rd02"), turn);
        ps.getLeaf("Rd01").split(4, "Rd02", turn);
        cnl.clear(); cnl.add("Ogre"); cnl.add("Ogre");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear(); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd02").revealSomeCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Lion");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Gargoyle");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Gargoyle");
        cnl.clear(); cnl.add("Lion");
        ps.getLeaf("Rd02").revealSomeCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Lion");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Titan");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Warlock");
        ps.getLeaf("Rd02").addCreature("Gargoyle");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        ps.printLeaves();
        ps.printLeaves();

        turn = 4;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").split(2, "Rd03", turn);
        ps.getLeaf("Rd02").split(2, "Rd04", turn);
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Cyclops");
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Rd02").revealSomeCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertFalse(ps.getLeaf("Rd04").allCertain());
        ps.printLeaves();

        turn = 5;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Warlock");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Warlock");
        ps.getLeaf("Rd02").addCreature("Ogre");
        cnl.clear(); cnl.add("Ogre"); cnl.add("Ogre");
        ps.getLeaf("Rd03").revealSomeCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Troll");
        cnl.clear(); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        ps.printLeaves();

        turn = 6;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd02").split(2, "Rd05", turn);
        cnl.clear(); 
        cnl.add("Titan"); cnl.add("Warlock"); cnl.add("Warlock");
        cnl.add("Cyclops"); cnl.add("Troll"); cnl.add("Gargoyle"); 
        cnl.add("Gargoyle");
        ps.getLeaf("Rd01").revealAllCreatures(cnl);
        ps.getLeaf("Rd01").removeCreature("Gargoyle");
        ps.getLeaf("Rd01").removeCreature("Gargoyle");
        ps.getLeaf("Rd02").removeCreature("Angel");
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear(); cnl.add("Lion"); cnl.add("Lion");
        ps.getLeaf("Rd02").revealSomeCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Minotaur");
        cnl.clear(); cnl.add("Lion");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Lion");
        cnl.clear();
        cnl.add("Cyclops"); cnl.add("Minotaur"); cnl.add("Lion");
        cnl.add("Lion"); cnl.add("Ogre");
        ps.getLeaf("Rd02").revealAllCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Minotaur");
        cnl.clear(); 
        cnl.add("Cyclops"); cnl.add("Minotaur"); cnl.add("Minotaur");
        cnl.add("Lion"); cnl.add("Lion"); cnl.add("Ogre");
        ps.getLeaf("Rd02").removeCreatures(cnl);
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 7;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd03").revealSomeCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Troll");
        cnl.clear(); cnl.add("Lion");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 8;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").split(2, "Rd02", turn);
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Cyclops");
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 9;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd03").revealSomeCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Troll");
        cnl.clear(); cnl.add("Lion"); cnl.add("Lion"); cnl.add("Lion");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Griffon");
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 10;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").split(2, "Rd06", turn);
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 11;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Griffon"); cnl.add("Lion"); cnl.add("Lion"); 
        cnl.add("Lion"); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd04").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Cyclops");
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd03").revealSomeCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 12;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd02").addCreature("Centaur");
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd03").revealSomeCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Warbear");
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 13;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Titan"); cnl.add("Warlock"); cnl.add("Warlock");
        cnl.add("Cyclops"); cnl.add("Cyclops"); cnl.add("Cyclops");
        ps.getLeaf("Rd01").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Cyclops"); cnl.add("Cyclops"); cnl.add("Cyclops");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Behemoth");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 14;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Griffon"); cnl.add("Lion"); cnl.add("Lion");
        cnl.add("Lion"); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd04").revealAllCreatures(cnl);
        ps.getLeaf("Rd02").removeCreature("Angel");
        ps.getLeaf("Rd04").addCreature("Angel");
        cnl.clear(); cnl.add("Angel"); cnl.add("Lion"); cnl.add("Lion");
        cnl.add("Lion"); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd04").removeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Angel");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        assertEquals(ps.getLeaf("Rd01").getHeight(), 6);
        assertEquals(ps.getLeaf("Rd02").getHeight(), 2);
        assertEquals(ps.getLeaf("Rd03").getHeight(), 7);
        assertEquals(ps.getLeaf("Rd04").getHeight(), 2);
        assertEquals(ps.getLeaf("Rd05").getHeight(), 6);
        assertEquals(ps.getLeaf("Rd06").getHeight(), 2);
    }

    public void testPredictSplits2()
    {
        ps = new PredictSplits("Red", "Rd11", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        Node root = ps.getLeaf("Rd11");
        assertTrue(root != null);
        assertTrue(ps.getLeaves(root) != null);
        ps.getLeaf("Rd11").split(4, "Rd10", turn);
        cnl.clear(); cnl.add("Ogre"); cnl.add("Ogre");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Troll");
        cnl.clear(); cnl.add("Gargoyle");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Gargoyle");
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Troll");
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Rd11").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 4;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Titan"); cnl.add("Ranger"); cnl.add("Troll");
            cnl.add("Troll"); cnl.add("Gargoyle"); cnl.add("Ogre"); 
            cnl.add("Ogre");
        ps.getLeaf("Rd10").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Gargoyle");
        ps.getLeaf("Rd10").removeCreatures(cnl);
        cnl.clear(); cnl.add("Angel");
        ps.getLeaf("Rd11").removeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Angel");
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 5;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd01", turn);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Troll");
        cnl.clear(); cnl.add("Ogre"); cnl.add("Ogre");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 6;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Troll"); cnl.add("Ogre"); cnl.add("Ogre");
        ps.getLeaf("Rd01").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Wyvern");
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Cyclops");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 7;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd06", turn);
        cnl.clear(); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 8;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd07", turn);
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll"); cnl.add("Ogre");
            cnl.add("Ogre");
        ps.getLeaf("Rd01").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Angel");
        ps.getLeaf("Rd10").removeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll"); cnl.add("Ogre");
            cnl.add("Ogre");
        ps.getLeaf("Rd01").removeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear(); cnl.add("Wyvern");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Wyvern");
        cnl.clear(); cnl.add("Lion");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 9;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd07").addCreature("Centaur");
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Cyclops");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 10;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd08", turn);
        cnl.clear(); cnl.add("Angel"); cnl.add("Angel");
        ps.getLeaf("Rd01").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd06").revealSomeCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Warbear");
        cnl.clear(); cnl.add("Centaur");
        ps.getLeaf("Rd07").revealSomeCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Centaur");
        cnl.clear(); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd08").revealSomeCreatures(cnl);
        ps.getLeaf("Rd08").addCreature("Lion");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear(); cnl.add("Cyclops"); cnl.add("Cyclops"); 
            cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Behemoth");
        cnl.clear(); cnl.add("Angel"); cnl.add("Angel");
        ps.getLeaf("Rd01").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Angel"); cnl.add("Angel");
        ps.getLeaf("Rd01").removeCreatures(cnl);
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 11;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd06").revealSomeCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Ranger");
        cnl.clear(); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd07").revealSomeCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Lion");
        cnl.clear(); cnl.add("Lion");
        ps.getLeaf("Rd08").revealSomeCreatures(cnl);
        ps.getLeaf("Rd08").addCreature("Lion");
        cnl.clear(); cnl.add("Titan");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Warlock");
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 12;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd05", turn);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Troll");
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd06").revealSomeCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Warbear");
        cnl.clear(); cnl.add("Lion");
        ps.getLeaf("Rd07").revealSomeCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Lion");
        cnl.clear(); cnl.add("Lion"); cnl.add("Lion");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd08").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 13;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd04", turn);
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Warbear");
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Rd07").revealSomeCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Cyclops");
        cnl.clear(); cnl.add("Lion"); cnl.add("Lion"); cnl.add("Centaur");
            cnl.add("Centaur");
        ps.getLeaf("Rd08").revealAllCreatures(cnl);
        ps.getLeaf("Rd08").removeCreatures(cnl);
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 14;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Warbear"); cnl.add("Warbear"); 
            cnl.add("Ranger"); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd06").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Cyclops");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd06").revealSomeCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Ranger");
        cnl.clear(); cnl.add("Wyvern"); cnl.add("Wyvern");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Hydra");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 15;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd07").split(2, "Rd02", turn);
        ps.getLeaf("Rd11").split(2, "Rd01", turn);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Troll");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd06").revealSomeCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Ranger");
        cnl.clear(); cnl.add("Cyclops"); cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Gorgon");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 16;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Warbear"); cnl.add("Warbear"); 
            cnl.add("Ranger"); cnl.add("Ranger"); cnl.add("Ranger"); 
            cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd06").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Ranger");
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Cyclops");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Ranger");
        cnl.clear(); cnl.add("Lion"); cnl.add("Lion");
        ps.getLeaf("Rd07").revealSomeCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Ranger");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd10").revealSomeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 17;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd06").split(2, "Rd08", turn);
        ps.getLeaf("Rd11").split(2, "Rd03", turn);
        cnl.clear(); cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd08").revealSomeCreatures(cnl);
        ps.getLeaf("Rd08").removeCreatures(cnl);
        cnl.clear(); cnl.add("Warbear");
        ps.getLeaf("Rd05").revealSomeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Warbear");
        cnl.clear(); cnl.add("Behemoth");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Behemoth");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 18;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd12", turn);
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Ranger");
        cnl.clear(); cnl.add("Gorgon");
        ps.getLeaf("Rd11").revealSomeCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Gorgon");
        cnl.clear(); cnl.add("Ranger"); cnl.add("Ranger");
        ps.getLeaf("Rd12").revealSomeCreatures(cnl);
        ps.getLeaf("Rd12").removeCreatures(cnl);
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 19;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd08", turn);
        cnl.clear(); cnl.add("Cyclops"); cnl.add("Ranger"); cnl.add("Lion"); 
            cnl.add("Lion"); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd07").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Lion"); cnl.add("Centaur"); cnl.add("Centaur");
        ps.getLeaf("Rd07").removeCreatures(cnl);
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd01").revealSomeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Ranger");
        cnl.clear(); cnl.add("Cyclops");
        ps.getLeaf("Rd03").revealSomeCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Cyclops");
        cnl.clear(); cnl.add("Cyclops"); cnl.add("Cyclops");
        ps.getLeaf("Rd04").revealSomeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Gorgon");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd07").revealSomeCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Ranger");
        cnl.clear(); cnl.add("Ranger");
        ps.getLeaf("Rd08").revealSomeCreatures(cnl);
        ps.getLeaf("Rd08").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();

        turn = 20;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Gorgon"); cnl.add("Cyclops"); cnl.add("Cyclops"); 
            cnl.add("Cyclops"); cnl.add("Lion");
        ps.getLeaf("Rd04").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Titan"); cnl.add("Hydra"); cnl.add("Wyvern"); 
            cnl.add("Wyvern"); cnl.add("Warlock");
        ps.getLeaf("Rd10").revealAllCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Angel");
        cnl.clear(); cnl.add("Warbear"); cnl.add("Warbear"); 
            cnl.add("Ranger"); cnl.add("Ranger"); cnl.add("Troll"); 
            cnl.add("Troll"); cnl.add("Troll");
        ps.getLeaf("Rd05").revealAllCreatures(cnl);
        cnl.clear(); cnl.add("Troll");
        ps.getLeaf("Rd05").removeCreatures(cnl);
        cnl.clear(); cnl.add("Angel");
        ps.getLeaf("Rd10").removeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Angel");
        cnl.clear(); cnl.add("Angel"); cnl.add("Warbear"); cnl.add("Warbear"); 
            cnl.add("Ranger"); cnl.add("Ranger"); cnl.add("Troll"); 
        ps.getLeaf("Rd05").removeCreatures(cnl);
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printLeaves();
    }

    public void testPredictSplits3()
    {
        ps = new PredictSplits("Green", "Gr07", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        Node root = ps.getLeaf("Gr07");
        assertTrue(root != null);
        assertTrue(ps.getLeaves(root) != null);
        ps.getLeaf("Gr07").split(4, "Gr11", turn);
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Gr07").revealSomeCreatures(cnl);
        ps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear(); cnl.add("Centaur");
        ps.getLeaf("Gr11").revealSomeCreatures(cnl);
        ps.getLeaf("Gr11").addCreature("Centaur");
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Gargoyle"); cnl.add("Gargoyle");
        ps.getLeaf("Gr07").revealSomeCreatures(cnl);
        ps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear(); cnl.add("Ogre");
        ps.getLeaf("Gr11").revealSomeCreatures(cnl);
        ps.getLeaf("Gr11").addCreature("Ogre");
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear(); cnl.add("Centaur"); cnl.add("Centaur"); 
            cnl.add("Centaur");
        ps.getLeaf("Gr11").revealSomeCreatures(cnl);
        ps.getLeaf("Gr11").addCreature("Warbear");
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        ps.printLeaves();
    }

    public void testPredictSplits4()
    {
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Rd", "Rd12", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Rd12").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Bk", "Bk10", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bk10").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Br", "Br05", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br05").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Gd", "Gd08", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gd08").revealAllCreatures(cnl);
        turn = 1;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd12").split(4, "Rd01", 1);
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Lion");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Rd01").revealSomeCreatures(cnl);
        aps.getLeaf("Rd01").addCreature("Troll");
        aps.getLeaf("Bk10").split(4, "Bk03", 1);
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Lion");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bk10").revealSomeCreatures(cnl);
        aps.getLeaf("Bk10").addCreature("Cyclops");
        aps.getLeaf("Br05").split(4, "Br01", 1);
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        aps.getLeaf("Br01").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Lion");
        aps.getLeaf("Gd08").split(4, "Gd01", 1);
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd01").revealSomeCreatures(cnl);
        aps.getLeaf("Gd01").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Ogre");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Lion");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Rd01").revealSomeCreatures(cnl);
        aps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Bk10").revealSomeCreatures(cnl);
        aps.getLeaf("Bk10").addCreature("Ogre");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        aps.getLeaf("Br01").addCreature("Warlock");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Lion");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd01").revealSomeCreatures(cnl);
        aps.getLeaf("Gd01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Ogre");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bk10").revealSomeCreatures(cnl);
        aps.getLeaf("Bk10").addCreature("Warlock");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        aps.getLeaf("Br01").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Centaur");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd01").revealSomeCreatures(cnl);
        aps.getLeaf("Gd01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Troll");
        turn = 4;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd12").split(2, "Rd11", 4);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Warlock");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Rd11").revealSomeCreatures(cnl);
        aps.getLeaf("Rd11").addCreature("Centaur");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd01").revealSomeCreatures(cnl);
        aps.getLeaf("Rd01").addCreature("Gargoyle");
        aps.getLeaf("Bk10").split(2, "Bk04", 4);
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Troll");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Bk10").revealSomeCreatures(cnl);
        aps.getLeaf("Bk10").addCreature("Cyclops");
        aps.getLeaf("Br01").split(2, "Br02", 4);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        aps.getLeaf("Br01").addCreature("Warlock");
        aps.getLeaf("Gd01").split(2, "Gd04", 4);
        aps.getLeaf("Gd08").split(2, "Gd02", 4);
        turn = 5;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd01").split(2, "Rd07", 5);
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Rd01").revealSomeCreatures(cnl);
        aps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Cyclops");
        aps.getLeaf("Bk03").split(2, "Bk12", 5);
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Bk10").revealSomeCreatures(cnl);
        aps.getLeaf("Bk10").addCreature("Ogre");
        aps.getLeaf("Br05").split(2, "Br10", 5);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        aps.getLeaf("Br01").addCreature("Warlock");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Centaur");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gd01").revealSomeCreatures(cnl);
        aps.getLeaf("Gd01").addCreature("Lion");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd02").revealSomeCreatures(cnl);
        aps.getLeaf("Gd02").addCreature("Cyclops");
        turn = 6;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd12").split(2, "Rd02", 6);
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Rd11").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd04").revealAllCreatures(cnl);
        aps.getLeaf("Gd04").removeCreature("Gargoyle");
        aps.getLeaf("Rd11").removeCreature("Centaur");
        aps.getLeaf("Gd04").removeCreature("Gargoyle");
        aps.getLeaf("Rd11").removeCreature("Centaur");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Rd11").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Rd11").revealSomeCreatures(cnl);
        aps.getLeaf("Rd11").addCreature("Centaur");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd02").revealSomeCreatures(cnl);
        aps.getLeaf("Rd02").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Ranger");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd01").revealSomeCreatures(cnl);
        aps.getLeaf("Rd01").addCreature("Cyclops");
        aps.getLeaf("Bk10").split(2, "Bk09", 6);
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Lion");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Bk10").revealSomeCreatures(cnl);
        aps.getLeaf("Bk10").addCreature("Ogre");
        aps.getLeaf("Br01").split(2, "Br08", 6);
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Br01").revealSomeCreatures(cnl);
        aps.getLeaf("Br01").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Ogre");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Lion");
        aps.printLeaves();
    }


    public void testPredictSplits5()
    {
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Rd", "Rd12", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Rd12").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Gd", "Gd12", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gd12").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Br", "Br02", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br02").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Gr", "Gr07", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gr07").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Bk", "Bk07", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bk07").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Bu", "Bu05", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bu05").revealAllCreatures(cnl);
        turn = 1;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd12").split(4, "Rd09", 1);
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Troll");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Gargoyle");
        aps.getLeaf("Gd12").split(4, "Gd08", 1);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Centaur");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        aps.getLeaf("Gd12").addCreature("Warlock");
        aps.getLeaf("Br02").split(4, "Br07", 1);
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Troll");
        aps.getLeaf("Gr07").split(4, "Gr02", 1);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Centaur");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Warlock");
        aps.getLeaf("Bk07").split(4, "Bk03", 1);
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Centaur");
        aps.getLeaf("Bu05").split(4, "Bu01", 1);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bu05").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Bu01").revealSomeCreatures(cnl);
        aps.getLeaf("Bu01").addCreature("Centaur");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bu05").revealSomeCreatures(cnl);
        aps.getLeaf("Bu05").addCreature("Warlock");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Warbear");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        aps.getLeaf("Gd12").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Centaur");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Lion");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bu05").revealSomeCreatures(cnl);
        aps.getLeaf("Bu05").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Lion");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Ranger");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Centaur");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ogre");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Warlock");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bu05").revealSomeCreatures(cnl);
        aps.getLeaf("Bu05").addCreature("Cyclops");
        turn = 4;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd09").split(2, "Rd05", 4);
        aps.getLeaf("Rd12").split(2, "Rd11", 4);
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        aps.getLeaf("Gd12").addCreature("Troll");
        aps.getLeaf("Br02").split(2, "Br09", 4);
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Centaur");
        aps.getLeaf("Gr02").split(2, "Gr12", 4);
        aps.getLeaf("Gr07").split(2, "Gr01", 4);
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Lion");
        aps.getLeaf("Bk03").split(2, "Bk06", 4);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Warlock");
        aps.getLeaf("Bu05").split(2, "Bu09", 4);
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Bu05").revealSomeCreatures(cnl);
        aps.getLeaf("Bu05").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Cyclops");
        turn = 5;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gd08").split(2, "Gd01", 5);
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd01").revealSomeCreatures(cnl);
        aps.getLeaf("Gd01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Warbear");
        aps.getLeaf("Br07").split(2, "Br06", 5);
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br07").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Rd05").revealAllCreatures(cnl);
        aps.getLeaf("Rd05").removeCreature("Gargoyle");
        aps.getLeaf("Rd05").removeCreature("Gargoyle");
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Br07").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Warbear");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Lion");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Ogre");
        aps.getLeaf("Bk07").split(2, "Bk04", 5);
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bk04").revealSomeCreatures(cnl);
        aps.getLeaf("Bk04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Lion");
        turn = 6;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gd12").split(2, "Gd11", 6);
        aps.getLeaf("Gd01").addCreature("Ogre");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gd08").revealSomeCreatures(cnl);
        aps.getLeaf("Gd08").addCreature("Lion");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        aps.getLeaf("Gd12").addCreature("Warlock");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Warbear"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Warbear");
        aps.getLeaf("Gr02").split(2, "Gr09", 6);
        aps.getLeaf("Gr01").addCreature("Ogre");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Bk04").revealSomeCreatures(cnl);
        aps.getLeaf("Bk04").addCreature("Cyclops");
        aps.getLeaf("Bk07").addCreature("Ogre");
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Bu05").revealSomeCreatures(cnl);
        aps.getLeaf("Bu05").addCreature("Behemoth");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Lion");
        turn = 7;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gd08").split(2, "Gd06", 7);
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        aps.getLeaf("Gd12").addCreature("Troll");
        aps.getLeaf("Gr07").split(2, "Gr03", 7);
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gr01").revealSomeCreatures(cnl);
        aps.getLeaf("Gr01").addCreature("Ogre");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Troll");
        turn = 8;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd12").split(2, "Rd01", 8);
        aps.getLeaf("Rd09").split(2, "Rd11", 8);
        aps.getLeaf("Rd09").merge(aps.getLeaf("Rd11"), turn);
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gd01").revealSomeCreatures(cnl);
        aps.getLeaf("Gd01").addCreature("Ogre");
        aps.getLeaf("Br07").split(2, "Br01", 8);
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gr02").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bu01").revealAllCreatures(cnl);
        aps.getLeaf("Bu01").removeCreature("Centaur");
        aps.getLeaf("Gr02").removeCreature("Ranger");
        aps.getLeaf("Bu01").removeCreature("Angel");
        aps.getLeaf("Gr02").removeCreature("Angel");
        aps.getLeaf("Bu01").removeCreature("Ogre");
        aps.getLeaf("Gr02").removeCreature("Lion");
        aps.getLeaf("Bu01").removeCreature("Centaur");
        aps.getLeaf("Gr02").removeCreature("Ranger");
        aps.getLeaf("Bu01").removeCreature("Centaur");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Gr02").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gr01").revealSomeCreatures(cnl);
        aps.getLeaf("Gr01").addCreature("Troll");
        aps.getLeaf("Bk07").split(2, "Bk06", 8);
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Bk06").revealSomeCreatures(cnl);
        aps.getLeaf("Bk06").addCreature("Ogre");
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Troll");
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Behemoth"); 
        cnl.add("Warlock"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bu05").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Warlock"); 
        cnl.add("Warlock"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gd12").revealAllCreatures(cnl);
        aps.getLeaf("Gd12").removeCreature("Gargoyle");
        aps.getLeaf("Bu05").removeCreature("Cyclops");
        aps.getLeaf("Gd12").removeCreature("Troll");
        aps.getLeaf("Bu05").removeCreature("Cyclops");
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Gd12").revealSomeCreatures(cnl);
        aps.getLeaf("Gd12").addCreature("Troll");
        aps.getLeaf("Gd12").removeCreature("Troll");
        aps.getLeaf("Bu05").removeCreature("Ogre");
        aps.getLeaf("Gd12").removeCreature("Troll");
        aps.getLeaf("Bu05").removeCreature("Warlock");
        aps.getLeaf("Gd12").removeCreature("Warlock");
        aps.getLeaf("Gd12").removeCreature("Troll");
        aps.getLeaf("Bu05").removeCreature("Behemoth");
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Warlock"); 
        aps.getLeaf("Gd12").revealAllCreatures(cnl);
        turn = 9;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd09").split(2, "Rd02", 9);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Cyclops"); 
        cnl.add("Ranger"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Warlock"); 
        aps.getLeaf("Gd12").revealAllCreatures(cnl);
        aps.getLeaf("Rd12").removeCreature("Ranger");
        aps.getLeaf("Gd12").removeCreature("Warlock");
        aps.getLeaf("Rd12").removeCreature("Troll");
        aps.getLeaf("Rd09").removeCreature("Angel");
        aps.getLeaf("Rd12").addCreature("Angel");
        aps.getLeaf("Gd12").removeCreature("Titan");
        aps.getLeaf("Rd12").removeCreature("Cyclops");
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Troll");
        cnl.clear();
        cnl.add("Warbear"); 
        cnl.add("Warbear"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Giant");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr01").revealSomeCreatures(cnl);
        aps.getLeaf("Gr01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Lion");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Lion");
        turn = 10;
        Log.debug("Turn " + turn);
        aps.getLeaf("Br02").split(2, "Br04", 10);
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Behemoth");
        cnl.clear();
        cnl.add("Warbear"); 
        cnl.add("Warbear"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Unicorn");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gr01").revealSomeCreatures(cnl);
        aps.getLeaf("Gr01").addCreature("Troll");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Griffon");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Warlock");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Troll");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Ranger");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Griffon");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Centaur");
        turn = 11;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr01").split(2, "Gr06", 11);
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Behemoth");
        aps.getLeaf("Bk07").split(2, "Bk12", 11);
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Bk06").revealSomeCreatures(cnl);
        aps.getLeaf("Bk06").addCreature("Troll");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Ranger");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Ranger");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Warlock");
        turn = 12;
        Log.debug("Turn " + turn);
        aps.getLeaf("Br02").split(2, "Br01", 12);
        aps.getLeaf("Br07").split(2, "Br05", 12);
        aps.getLeaf("Br07").addCreature("Angel");
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Troll");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Gr01").revealSomeCreatures(cnl);
        aps.getLeaf("Gr01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gr03").revealSomeCreatures(cnl);
        aps.getLeaf("Gr03").addCreature("Ogre");
        aps.getLeaf("Bk03").split(2, "Bk09", 12);
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Ranger");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Br06").revealSomeCreatures(cnl);
        aps.getLeaf("Br06").addCreature("Lion");
        aps.getLeaf("Gr02").addCreature("Angel");
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gr01").revealSomeCreatures(cnl);
        aps.getLeaf("Gr01").addCreature("Troll");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Centaur"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Centaur");
        turn = 14;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd09").split(2, "Rd11", 14);
        aps.getLeaf("Rd12").split(2, "Rd03", 14);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Ranger");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Wyvern");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd03").revealSomeCreatures(cnl);
        aps.getLeaf("Rd03").addCreature("Ranger");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Wyvern");
        cnl.clear();
        cnl.add("Unicorn"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Unicorn");
        aps.getLeaf("Gr01").split(2, "Gr12", 14);
        aps.getLeaf("Gr07").split(2, "Gr04", 14);
        cnl.clear();
        cnl.add("Ogre"); 
        aps.getLeaf("Gr12").revealSomeCreatures(cnl);
        aps.getLeaf("Gr12").addCreature("Ogre");
        aps.getLeaf("Bk07").split(2, "Bk04", 14);
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Warbear");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Cyclops");
        turn = 15;
        Log.debug("Turn " + turn);
        aps.getLeaf("Br07").split(2, "Br10", 15);
        aps.getLeaf("Gr02").split(2, "Gr05", 15);
        cnl.clear();
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        cnl.add("Ogre"); 
        aps.getLeaf("Gr03").revealSomeCreatures(cnl);
        aps.getLeaf("Gr03").addCreature("Minotaur");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr06").revealSomeCreatures(cnl);
        aps.getLeaf("Gr06").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Cyclops");
        aps.getLeaf("Bk03").split(2, "Bk09", 15);
        cnl.clear();
        cnl.add("Griffon"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        cnl.add("Lion"); 
        aps.getLeaf("Rd09").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Lion"); 
        aps.getLeaf("Bk03").revealAllCreatures(cnl);
        aps.getLeaf("Bk03").removeCreature("Lion");
        aps.getLeaf("Bk03").removeCreature("Cyclops");
        aps.getLeaf("Rd09").removeCreature("Ranger");
        aps.getLeaf("Rd03").removeCreature("Angel");
        aps.getLeaf("Rd09").addCreature("Angel");
        aps.getLeaf("Bk03").removeCreature("Angel");
        aps.getLeaf("Rd09").removeCreature("Lion");
        aps.getLeaf("Bk03").removeCreature("Cyclops");
        aps.getLeaf("Rd09").removeCreature("Cyclops");
        aps.getLeaf("Bk03").removeCreature("Cyclops");
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Griffon"); 
        cnl.add("Cyclops"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Rd09").revealAllCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Angel");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Warbear"); 
        cnl.add("Warbear"); 
        aps.getLeaf("Br10").revealSomeCreatures(cnl);
        aps.getLeaf("Br10").addCreature("Unicorn");
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Warbear"); 
        aps.getLeaf("Bk07").revealSomeCreatures(cnl);
        aps.getLeaf("Bk07").addCreature("Warbear");
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Behemoth");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Ranger");
        turn = 17;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr07").split(2, "Gr03", 17);
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        turn = 18;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd09").split(2, "Rd01", 18);
        cnl.clear();
        cnl.add("Griffon"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Griffon");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Rd11").revealSomeCreatures(cnl);
        aps.getLeaf("Rd11").addCreature("Lion");
        cnl.clear();
        cnl.add("Centaur"); 
        cnl.add("Centaur"); 
        aps.getLeaf("Br04").revealSomeCreatures(cnl);
        aps.getLeaf("Br04").addCreature("Lion");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Ranger");
        cnl.clear();
        cnl.add("Griffon"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Griffon");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Gr03").revealSomeCreatures(cnl);
        aps.getLeaf("Gr03").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Warlock");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd03").revealSomeCreatures(cnl);
        aps.getLeaf("Rd03").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Ranger");
        turn = 19;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr02").split(2, "Gr12", 19);
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        aps.getLeaf("Bk07").split(2, "Bk03", 19);
        aps.getLeaf("Bk07").addCreature("Angel");
        turn = 20;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd12").split(2, "Rd10", 20);
        aps.getLeaf("Rd09").split(2, "Rd05", 20);
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Rd05").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Bk04").revealAllCreatures(cnl);
        aps.getLeaf("Bk04").removeCreature("Ranger");
        aps.getLeaf("Rd05").removeCreature("Ranger");
        aps.getLeaf("Rd01").removeCreature("Angel");
        aps.getLeaf("Rd05").addCreature("Angel");
        aps.getLeaf("Bk04").removeCreature("Ranger");
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Angel"); 
        aps.getLeaf("Rd05").revealAllCreatures(cnl);
        aps.getLeaf("Rd05").addCreature("Angel");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Ranger");
        cnl.clear();
        cnl.add("Wyvern"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Wyvern");
        aps.getLeaf("Br02").split(2, "Br09", 20);
        cnl.clear();
        cnl.add("Behemoth"); 
        cnl.add("Behemoth"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Serpent");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Gr05").revealSomeCreatures(cnl);
        aps.getLeaf("Gr05").addCreature("Lion");
        cnl.clear();
        cnl.add("Behemoth"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Behemoth");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Bk03").revealSomeCreatures(cnl);
        aps.getLeaf("Bk03").addCreature("Ranger");
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Wyvern"); 
        cnl.add("Wyvern"); 
        cnl.add("Warlock"); 
        cnl.add("Warlock"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd12").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Angel"); 
        cnl.add("Warlock"); 
        cnl.add("Warlock"); 
        cnl.add("Warbear"); 
        cnl.add("Warbear"); 
        aps.getLeaf("Bk07").revealAllCreatures(cnl);
        aps.getLeaf("Bk07").removeCreature("Warbear");
        aps.getLeaf("Rd12").removeCreature("Wyvern");
        aps.getLeaf("Rd05").removeCreature("Angel");
        aps.getLeaf("Rd12").addCreature("Angel");
        aps.getLeaf("Bk07").removeCreature("Angel");
        aps.getLeaf("Rd12").removeCreature("Angel");
        aps.getLeaf("Bk07").removeCreature("Warbear");
        aps.getLeaf("Bk07").removeCreature("Warlock");
        aps.getLeaf("Bk07").removeCreature("Warlock");
        aps.getLeaf("Rd12").removeCreature("Warlock");
        aps.getLeaf("Rd12").removeCreature("Troll");
        aps.getLeaf("Bk07").removeCreature("Titan");
        cnl.clear();
        cnl.add("Titan"); 
        cnl.add("Wyvern"); 
        cnl.add("Warlock"); 
        aps.getLeaf("Rd12").revealAllCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Angel");
        cnl.clear();
        cnl.add("Troll"); 
        aps.getLeaf("Rd10").revealSomeCreatures(cnl);
        aps.getLeaf("Rd10").addCreature("Troll");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd03").revealSomeCreatures(cnl);
        aps.getLeaf("Rd03").addCreature("Ranger");
        cnl.clear();
        cnl.add("Gorgon"); 
        aps.getLeaf("Br02").revealSomeCreatures(cnl);
        aps.getLeaf("Br02").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Cyclops"); 
        aps.getLeaf("Br09").revealSomeCreatures(cnl);
        aps.getLeaf("Br09").addCreature("Cyclops");
        turn = 21;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr02").split(2, "Gr04", 21);
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Lion"); 
        aps.getLeaf("Gr05").revealSomeCreatures(cnl);
        aps.getLeaf("Gr05").addCreature("Lion");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr06").revealSomeCreatures(cnl);
        aps.getLeaf("Gr06").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Griffon"); 
        cnl.add("Griffon"); 
        aps.getLeaf("Rd09").revealSomeCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Hydra");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Warlock");
        turn = 22;
        Log.debug("Turn " + turn);
        aps.getLeaf("Br02").split(2, "Br11", 22);
        aps.getLeaf("Br05").split(2, "Br04", 22);
        cnl.clear();
        cnl.add("Giant"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Giant");
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Griffon"); 
        cnl.add("Griffon"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Angel"); 
        aps.getLeaf("Rd05").revealAllCreatures(cnl);
        aps.getLeaf("Gr02").removeCreature("Griffon");
        aps.getLeaf("Rd05").removeCreature("Angel");
        aps.getLeaf("Gr02").removeCreature("Ranger");
        aps.getLeaf("Rd05").removeCreature("Angel");
        cnl.clear();
        cnl.add("Angel"); 
        cnl.add("Griffon"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr04").revealSomeCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Ranger");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Gr05").revealSomeCreatures(cnl);
        aps.getLeaf("Gr05").addCreature("Minotaur");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Rd10").revealSomeCreatures(cnl);
        aps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear();
        cnl.add("Troll"); 
        cnl.add("Troll"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Warbear");
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Br09").revealSomeCreatures(cnl);
        aps.getLeaf("Br09").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Guardian");
        cnl.clear();
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        cnl.add("Ranger"); 
        aps.getLeaf("Gr04").revealSomeCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Guardian");
        cnl.clear();
        cnl.add("Lion"); 
        cnl.add("Lion"); 
        aps.getLeaf("Gr05").revealSomeCreatures(cnl);
        aps.getLeaf("Gr05").addCreature("Ranger");
        cnl.clear();
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr06").revealSomeCreatures(cnl);
        aps.getLeaf("Gr06").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gorgon"); 
        aps.getLeaf("Gr07").revealSomeCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Titan"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        cnl.clear();
        cnl.add("Wyvern"); 
        aps.getLeaf("Rd12").revealSomeCreatures(cnl);
        aps.getLeaf("Rd12").addCreature("Wyvern");
        turn = 24;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr07").split(2, "Gr08", 24);
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr02").revealSomeCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Gr04").revealSomeCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Ranger");
        turn = 25;
        Log.debug("Turn " + turn);
        aps.getLeaf("Rd09").split(2, "Rd08", 25);
        cnl.clear();
        cnl.add("Hydra"); 
        cnl.add("Griffon"); 
        cnl.add("Griffon"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Rd09").revealAllCreatures(cnl);
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        cnl.add("Gargoyle"); 
        cnl.add("Gargoyle"); 
        aps.getLeaf("Gr06").revealAllCreatures(cnl);
        aps.getLeaf("Gr06").removeCreature("Gargoyle");
        aps.getLeaf("Rd12").removeCreature("Angel");
        aps.getLeaf("Rd09").addCreature("Angel");
        aps.getLeaf("Gr06").removeCreature("Cyclops");
        aps.getLeaf("Gr06").removeCreature("Cyclops");
        aps.getLeaf("Gr06").removeCreature("Gargoyle");
        aps.getLeaf("Gr06").removeCreature("Cyclops");
        cnl.clear();
        cnl.add("Hydra"); 
        cnl.add("Angel"); 
        cnl.add("Griffon"); 
        cnl.add("Griffon"); 
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Rd09").revealAllCreatures(cnl);
        aps.getLeaf("Rd09").addCreature("Angel");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Rd03").revealSomeCreatures(cnl);
        aps.getLeaf("Rd03").addCreature("Troll");
        aps.getLeaf("Rd03").removeCreature("Troll");
        cnl.clear();
        cnl.add("Ranger"); 
        aps.getLeaf("Br05").revealSomeCreatures(cnl);
        aps.getLeaf("Br05").addCreature("Lion");
        cnl.clear();
        cnl.add("Unicorn"); 
        aps.getLeaf("Br07").revealSomeCreatures(cnl);
        aps.getLeaf("Br07").addCreature("Unicorn");
        cnl.clear();
        cnl.add("Cyclops"); 
        cnl.add("Cyclops"); 
        aps.getLeaf("Br09").revealSomeCreatures(cnl);
        aps.getLeaf("Br09").addCreature("Gorgon");
        aps.printLeaves();
    }
}

class AllPredictSplits
{
    private List pslist = new ArrayList();

    void add_ps(PredictSplits ps)
    {
        pslist.add(ps);
    }

    Node getLeaf(String markerId)
    {
        Iterator it = pslist.iterator();
        while (it.hasNext())
        {
            PredictSplits ps = (PredictSplits)it.next();
            Node leaf = ps.getLeaf(markerId);
            if (leaf != null)
            {
                return leaf;
            }
        }
        return null;
    }

    void printLeaves()
    {
        Iterator it = pslist.iterator();
        while (it.hasNext())
        {
            PredictSplits ps = (PredictSplits)it.next();
            ps.printLeaves();
        }
    }
}
