package net.sf.colossus.client;


import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import junit.framework.TestCase;
import net.sf.colossus.server.VariantSupport;
import net.sf.colossus.util.Log;


/**
 *  JUnit test for split prediction.
 *  @version $Id$
 *  @author David Ripton
 */
public class PredictSplitsTest extends TestCase
{
    List cnl;
    AllPredictSplits aps;
    PredictSplits ps;
    int turn = 0;

    public PredictSplitsTest(String name)
    {
        super(name);
    }

    protected void setUp()
    {
        VariantSupport.loadVariant("Default", true);
        aps = new AllPredictSplits();

        cnl = new ArrayList();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Ogre");
        cnl.add("Ogre");
    }

    public void testPredictSplits1()
    {
        Log.debug("testPredictSplits1()");
        ps = new PredictSplits("Red", "Rd01", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        Node root = ps.getLeaf("Rd01");
        assertTrue(root != null);
        assertTrue(ps.getLeaves(root) != null);
        ps.getLeaf("Rd01").split(4, "Rd02", turn);
        ps.getLeaf("Rd01").merge(ps.getLeaf("Rd02"), turn);
        ps.getLeaf("Rd01").split(4, "Rd02", turn);
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd02").revealCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Lion");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gargoyle");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Rd02").revealCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Lion");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Titan");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Warlock");
        ps.getLeaf("Rd02").addCreature("Gargoyle");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        ps.printLeaves();

        turn = 4;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").split(2, "Rd03", turn);
        ps.getLeaf("Rd02").split(2, "Rd04", turn);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Rd02").revealCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertFalse(ps.getLeaf("Rd04").allCertain());
        ps.printLeaves();

        turn = 5;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Warlock");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Warlock");
        ps.getLeaf("Rd02").addCreature("Ogre");
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd03").revealCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        ps.printLeaves();

        turn = 6;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd02").split(2, "Rd05", turn);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Warlock");
        cnl.add("Warlock");
        cnl.add("Cyclops");
        cnl.add("Troll");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").removeCreature("Gargoyle");
        ps.getLeaf("Rd01").removeCreature("Gargoyle");
        ps.getLeaf("Rd02").removeCreature("Angel");
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        ps.getLeaf("Rd02").revealCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Minotaur");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Lion");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Minotaur");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Ogre");
        ps.getLeaf("Rd02").revealCreatures(cnl);
        ps.getLeaf("Rd02").addCreature("Minotaur");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Minotaur");
        cnl.add("Minotaur");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Ogre");
        ps.getLeaf("Rd02").removeCreatures(cnl);
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 7;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd03").revealCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Troll");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 8;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").split(2, "Rd02", turn);
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 9;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd03").revealCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Troll");
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Lion");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Griffon");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        ps.printLeaves();

        turn = 10;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd01").split(2, "Rd06", turn);
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 11;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Griffon");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd03").revealCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 12;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd02").addCreature("Centaur");
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd03").revealCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Warbear");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 13;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Warlock");
        cnl.add("Warlock");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Behemoth");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        turn = 14;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Griffon");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd02").removeCreature("Angel");
        ps.getLeaf("Rd04").addCreature("Angel");
        cnl.clear();
        cnl.add("Angel");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd04").removeCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Angel");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertTrue(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        ps.printLeaves();

        assertEquals(ps.getLeaf("Rd01").getHeight(), 6);
        assertEquals(ps.getLeaf("Rd02").getHeight(), 2);
        assertEquals(ps.getLeaf("Rd03").getHeight(), 7);
        assertEquals(ps.getLeaf("Rd04").getHeight(), 2);
        assertEquals(ps.getLeaf("Rd05").getHeight(), 6);
        assertEquals(ps.getLeaf("Rd06").getHeight(), 2);
    }

    public void testPredictSplits2()
    {
        Log.debug("testPredictSplits2()");
        ps = new PredictSplits("Red", "Rd11", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        Node root = ps.getLeaf("Rd11");
        assertTrue(root != null);
        assertTrue(ps.getLeaves(root) != null);
        ps.getLeaf("Rd11").split(4, "Rd10", turn);
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Troll");
        cnl.clear();
        cnl.add("Gargoyle");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Gargoyle");
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Troll");
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Rd11").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 4;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Ranger");
        cnl.add("Troll");
        cnl.add("Troll");
        cnl.add("Gargoyle");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Gargoyle");
        ps.getLeaf("Rd10").removeCreatures(cnl);
        cnl.clear();
        cnl.add("Angel");
        ps.getLeaf("Rd11").removeCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Angel");
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 5;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd01", turn);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 6;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Troll");
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Wyvern");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Cyclops");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 7;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd06", turn);
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 8;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd07", turn);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Angel");
        ps.getLeaf("Rd10").removeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Rd01").removeCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Angel");
        cnl.clear();
        cnl.add("Wyvern");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Wyvern");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Lion");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 9;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd07").addCreature("Centaur");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Cyclops");
        assertTrue(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 10;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd08", turn);
        cnl.clear();
        cnl.add("Angel");
        cnl.add("Angel");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Warbear");
        cnl.clear();
        cnl.add("Centaur");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Centaur");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd08").revealCreatures(cnl);
        ps.getLeaf("Rd08").addCreature("Lion");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Behemoth");
        cnl.clear();
        cnl.add("Angel");
        cnl.add("Angel");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Angel");
        cnl.add("Angel");
        ps.getLeaf("Rd01").removeCreatures(cnl);
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 11;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Ranger");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Lion");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Rd08").revealCreatures(cnl);
        ps.getLeaf("Rd08").addCreature("Lion");
        cnl.clear();
        cnl.add("Titan");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Warlock");
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 12;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd05", turn);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Troll");
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Warbear");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Lion");
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd08").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertTrue(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 13;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd04", turn);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Warbear");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd08").revealCreatures(cnl);
        ps.getLeaf("Rd08").removeCreatures(cnl);
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 14;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Warbear");
        cnl.add("Warbear");
        cnl.add("Ranger");
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Ranger");
        cnl.clear();
        cnl.add("Wyvern");
        cnl.add("Wyvern");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Hydra");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 15;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd07").split(2, "Rd02", turn);
        ps.getLeaf("Rd11").split(2, "Rd01", turn);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Troll");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        ps.getLeaf("Rd06").addCreature("Ranger");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Gorgon");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertFalse(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 16;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Warbear");
        cnl.add("Warbear");
        cnl.add("Ranger");
        cnl.add("Ranger");
        cnl.add("Ranger");
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd06").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Ranger");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Ranger");
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 17;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd06").split(2, "Rd08", turn);
        ps.getLeaf("Rd11").split(2, "Rd03", turn);
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd08").revealCreatures(cnl);
        ps.getLeaf("Rd08").removeCreatures(cnl);
        cnl.clear();
        cnl.add("Warbear");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Warbear");
        cnl.clear();
        cnl.add("Behemoth");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Behemoth");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 18;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd10").split(2, "Rd12", turn);
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Ranger");
        cnl.clear();
        cnl.add("Gorgon");
        ps.getLeaf("Rd11").revealCreatures(cnl);
        ps.getLeaf("Rd11").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Ranger");
        cnl.add("Ranger");
        ps.getLeaf("Rd12").revealCreatures(cnl);
        ps.getLeaf("Rd12").removeCreatures(cnl);
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertFalse(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertFalse(ps.getLeaf("Rd07").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 19;
        Log.debug("Turn " + turn);
        ps.getLeaf("Rd11").split(2, "Rd08", turn);
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Ranger");
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Rd07").removeCreatures(cnl);
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd01").revealCreatures(cnl);
        ps.getLeaf("Rd01").addCreature("Ranger");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Rd03").revealCreatures(cnl);
        ps.getLeaf("Rd03").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        ps.getLeaf("Rd04").addCreature("Gorgon");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd07").revealCreatures(cnl);
        ps.getLeaf("Rd07").addCreature("Ranger");
        cnl.clear();
        cnl.add("Ranger");
        ps.getLeaf("Rd08").revealCreatures(cnl);
        ps.getLeaf("Rd08").addCreature("Ranger");
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 20;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gorgon");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Lion");
        ps.getLeaf("Rd04").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Hydra");
        cnl.add("Wyvern");
        cnl.add("Wyvern");
        cnl.add("Warlock");
        ps.getLeaf("Rd10").revealCreatures(cnl);
        ps.getLeaf("Rd10").addCreature("Angel");
        cnl.clear();
        cnl.add("Warbear");
        cnl.add("Warbear");
        cnl.add("Ranger");
        cnl.add("Ranger");
        cnl.add("Troll");
        cnl.add("Troll");
        cnl.add("Troll");
        ps.getLeaf("Rd05").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Troll");
        ps.getLeaf("Rd05").removeCreatures(cnl);
        cnl.clear();
        cnl.add("Angel");
        ps.getLeaf("Rd10").removeCreatures(cnl);
        ps.getLeaf("Rd05").addCreature("Angel");
        cnl.clear();
        cnl.add("Angel");
        cnl.add("Warbear");
        cnl.add("Warbear");
        cnl.add("Ranger");
        cnl.add("Ranger");
        cnl.add("Troll");
        ps.getLeaf("Rd05").removeCreatures(cnl);
        assertFalse(ps.getLeaf("Rd01").allCertain());
        assertTrue(ps.getLeaf("Rd02").allCertain());
        assertFalse(ps.getLeaf("Rd03").allCertain());
        assertTrue(ps.getLeaf("Rd04").allCertain());
        assertTrue(ps.getLeaf("Rd05").allCertain());
        assertTrue(ps.getLeaf("Rd06").allCertain());
        assertTrue(ps.getLeaf("Rd07").allCertain());
        assertFalse(ps.getLeaf("Rd08").allCertain());
        assertTrue(ps.getLeaf("Rd10").allCertain());
        assertFalse(ps.getLeaf("Rd11").allCertain());
        ps.printNodes();
        ps.printLeaves();
    }

    public void testPredictSplits3()
    {
        Log.debug("testPredictSplits3()");
        ps = new PredictSplits("Green", "Gr07", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        Node root = ps.getLeaf("Gr07");
        assertTrue(root != null);
        assertTrue(ps.getLeaves(root) != null);
        ps.getLeaf("Gr07").split(4, "Gr11", turn);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Gr07").revealCreatures(cnl);
        ps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur");
        ps.getLeaf("Gr11").revealCreatures(cnl);
        ps.getLeaf("Gr11").addCreature("Centaur");
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Gr07").revealCreatures(cnl);
        ps.getLeaf("Gr07").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ogre");
        ps.getLeaf("Gr11").revealCreatures(cnl);
        ps.getLeaf("Gr11").addCreature("Ogre");
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        ps.printNodes();
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Gr11").revealCreatures(cnl);
        ps.getLeaf("Gr11").addCreature("Warbear");
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        ps.printNodes();
        ps.printLeaves();
    }

    public void testPredictSplits4()
    {
        Log.debug("testPredictSplits4()");
        CreatureInfoList cil = new CreatureInfoList();
        cil.add(new CreatureInfo("Angel", true, true));
        cil.add(new CreatureInfo("Gargoyle", true, true));
        cil.add(new CreatureInfo("Centaur", true, true));
        cil.add(new CreatureInfo("Centaur", false, true));
        cil.add(new CreatureInfo("Centaur", true, false));
        Node n = new Node("Gd10", 1, cil, null);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        n.revealCreatures(cnl);
        assertTrue(n.allCertain());
    }

    public void testPredictSplits5()
    {
        Log.debug("testPredictSplits5()");
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Bk", "Bk06", cnl);
        ps.printLeaves();

        turn = 1;
        Log.debug("Turn " + turn);
        ps.getLeaf("Bk06").split(4, "Bk09", turn);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Ogre");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Ogre");
        assertFalse(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Bk06").revealCreatures(cnl);
        ps.getLeaf("Bk06").addCreature("Lion");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Cyclops");
        assertFalse(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 4;
        Log.debug("Turn " + turn);
        ps.getLeaf("Bk09").split(2, "Bk10", turn);
        cnl.clear();
        cnl.add("Titan");
        ps.getLeaf("Bk06").revealCreatures(cnl);
        ps.getLeaf("Bk06").addCreature("Warlock");
        ps.getLeaf("Bk09").addCreature("Ogre");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        assertFalse(ps.getLeaf("Bk10").allCertain());
        ps.printLeaves();

        turn = 5;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Bk06").revealCreatures(cnl);
        ps.getLeaf("Bk06").addCreature("Lion");
        cnl.clear();
        cnl.add("Cyclops");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Cyclops");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        assertFalse(ps.getLeaf("Bk10").allCertain());
        ps.printLeaves();
        ps.getLeaf("Bk10").removeCreature("Gargoyle");
        ps.getLeaf("Bk10").removeCreature("Gargoyle");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertTrue(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();
    }

    public void testPredictSplits6()
    {
        Log.debug("testPredictSplits6()");
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Bk", "Bk06", cnl);

        turn = 1;
        Log.debug("Turn " + turn);
        ps.getLeaf("Bk06").split(4, "Bk09", turn);
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Bk06").revealCreatures(cnl);
        ps.getLeaf("Bk06").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Lion");
        assertFalse(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps.getLeaf("Bk06").revealCreatures(cnl);
        ps.getLeaf("Bk06").addCreature("Troll");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Lion");
        assertFalse(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 4;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gargoyle");
        ps.getLeaf("Bk06").revealCreatures(cnl);
        ps.getLeaf("Bk06").addCreature("Gargoyle");
        ps.getLeaf("Bk09").addCreature("Centaur");
        assertFalse(ps.getLeaf("Bk06").allCertain());
        assertFalse(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 5;
        Log.debug("Turn " + turn);
        ps.getLeaf("Bk06").split(2, "Bk08", turn);
        ps.getLeaf("Bk09").split(2, "Bk11", turn);
        cnl.clear();
        cnl.add("Angel");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        ps.getLeaf("Bk08").revealCreatures(cnl);
        ps.getLeaf("Bk08").removeCreature("Gargoyle");
        ps.getLeaf("Bk09").removeCreature("Angel");
        ps.getLeaf("Bk08").addCreature("Angel");
        ps.getLeaf("Bk08").removeCreature("Gargoyle");
        ps.getLeaf("Bk08").removeCreature("Angel");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Lion");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        ps.getLeaf("Bk11").revealCreatures(cnl);
        ps.getLeaf("Bk11").addCreature("Lion");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertTrue(ps.getLeaf("Bk09").allCertain());
        assertTrue(ps.getLeaf("Bk11").allCertain());
        ps.printLeaves();

        turn = 6;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Lion");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Guardian");
        cnl.clear();
        cnl.add("Lion");
        ps.getLeaf("Bk11").revealCreatures(cnl);
        ps.getLeaf("Bk11").addCreature("Lion");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertTrue(ps.getLeaf("Bk09").allCertain());
        assertTrue(ps.getLeaf("Bk11").allCertain());
        ps.printLeaves();

        turn = 7;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Lion");
        cnl.add("Lion");
        ps.getLeaf("Bk09").revealCreatures(cnl);
        ps.getLeaf("Bk09").addCreature("Griffon");
        ps.getLeaf("Bk11").removeCreature("Lion");
        ps.getLeaf("Bk11").removeCreature("Lion");
        ps.getLeaf("Bk11").removeCreature("Centaur");
        ps.getLeaf("Bk11").removeCreature("Centaur");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertTrue(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();

        turn = 8;
        Log.debug("Turn " + turn);
        ps.getLeaf("Bk09").split(2, "Bk12", turn);
        ps.getLeaf("Bk12").removeCreature("Gargoyle");
        ps.getLeaf("Bk12").removeCreature("Centaur");
        assertTrue(ps.getLeaf("Bk06").allCertain());
        assertTrue(ps.getLeaf("Bk09").allCertain());
        ps.printLeaves();
    }

    public void testPredictSplits7()
    {
        Log.debug("testPredictSplits7()");
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Gr", "Gr08", cnl);
        aps.add_ps(ps);
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.printLeaves();

        turn = 1;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr08").split(4, "Gr04", turn);
        cnl.clear();
        cnl.add("Titan");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Titan");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Warlock");
        cnl.clear();
        cnl.add("Centaur");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Centaur");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 2;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gargoyle");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Gargoyle");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 3;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Cyclops");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 4;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr04").split(2, "Gr06", turn);
        cnl.clear();
        cnl.add("Ogre");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Ogre");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Lion");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr06").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 5;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Cyclops");
        aps.getLeaf("Gr06").addCreature("Ogre");
        cnl.clear();
        cnl.add("Lion");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Lion");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr06").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());
        assertEquals(ps.getLeaf("Gr06").getCertainCreatures().size(), 1);

        turn = 6;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr04").split(2, "Gr07", turn);
        aps.getLeaf("Gr08").split(2, "Gr11", turn);
        cnl.clear();
        cnl.add("Titan");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Warlock");
        cnl.clear();
        cnl.add("Ogre");
        aps.getLeaf("Gr06").revealCreatures(cnl);
        aps.getLeaf("Gr06").addCreature("Ogre");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        aps.getLeaf("Gr11").removeCreatures(cnl);
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr06").allCertain());
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 7;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr06").revealCreatures(cnl);
        aps.getLeaf("Gr06").addCreature("Troll");
        cnl.clear();
        cnl.add("Ogre");
        aps.getLeaf("Gr07").revealCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Ogre");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr06").allCertain());
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 8;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr04").split(2, "Gr12", turn);
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr07").revealCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Minotaur");
        cnl.clear();
        cnl.add("Gargoyle");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Troll");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr06").removeCreatures(cnl);
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Ogre");
        aps.getLeaf("Gr12").removeCreatures(cnl);
        aps.printLeaves();
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertTrue(ps.getLeaf("Gr08").allCertain());

        turn = 9;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Cyclops");
        aps.printLeaves();
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertTrue(ps.getLeaf("Gr08").allCertain());

        turn = 11;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr08").split(2, "Gr01", turn);
        cnl.clear();
        cnl.add("Titan");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Warlock");
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Cyclops");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr01").allCertain());
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 12;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Lion");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Lion");
        aps.printLeaves();
        aps.getLeaf("Gr01").removeCreature("Gargoyle");
        aps.getLeaf("Gr01").removeCreature("Gargoyle");
        aps.printLeaves();
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertTrue(ps.getLeaf("Gr08").allCertain());

        turn = 13;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr08").split(2, "Gr02", turn);
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr07").revealCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Troll");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 14;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr04").split(2, "Gr06", turn);
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr06").revealCreatures(cnl);
        aps.getLeaf("Gr06").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Cyclops");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr06").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 15;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr06").removeCreature("Cyclops");
        aps.getLeaf("Gr06").removeCreature("Cyclops");
        aps.getLeaf("Gr06").removeCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Centaur");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 16;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Ogre");
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr07").revealCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Minotaur");
        cnl.clear();
        cnl.add("Lion");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Lion");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());

        turn = 17;
        Log.debug("Turn " + turn);
        cnl.clear();
        cnl.add("Lion");
        cnl.add("Centaur");
        cnl.add("Centaur");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").removeCreature("Centaur");
        aps.getLeaf("Gr02").removeCreature("Lion");
        aps.getLeaf("Gr02").removeCreature("Centaur");
        aps.printLeaves();
        aps.getLeaf("Gr08").split(2, "Gr12", turn);
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Gorgon");
        aps.printLeaves();
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());
        assertFalse(ps.getLeaf("Gr12").allCertain());

        turn = 18;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr12").removeCreature("Lion");
        aps.getLeaf("Gr12").removeCreature("Lion");
        aps.getLeaf("Gr04").split(2, "Gr12", turn);
        aps.getLeaf("Gr07").split(2, "Gr09", turn);
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Gorgon");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr07").allCertain());
        assertTrue(ps.getLeaf("Gr08").allCertain());
        assertFalse(ps.getLeaf("Gr09").allCertain());
        assertFalse(ps.getLeaf("Gr12").allCertain());

        turn = 19;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr08").split(2, "Gr06", turn);
        aps.getLeaf("Gr09").removeCreature("Ogre");
        aps.getLeaf("Gr09").removeCreature("Ogre");
        cnl.clear();
        cnl.add("Minotaur");
        cnl.add("Minotaur");
        aps.getLeaf("Gr07").revealCreatures(cnl);
        aps.getLeaf("Gr07").addCreature("Unicorn");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Gorgon");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertFalse(ps.getLeaf("Gr06").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertFalse(ps.getLeaf("Gr08").allCertain());
        assertFalse(ps.getLeaf("Gr12").allCertain());

        turn = 20;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr06").removeCreature("Gorgon");
        aps.getLeaf("Gr06").removeCreature("Lion");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        aps.getLeaf("Gr08").revealCreatures(cnl);
        aps.getLeaf("Gr08").addCreature("Behemoth");
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr12").revealCreatures(cnl);
        aps.getLeaf("Gr12").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Cyclops");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertTrue(ps.getLeaf("Gr08").allCertain());
        assertFalse(ps.getLeaf("Gr12").allCertain());

        turn = 21;
        Log.debug("Turn " + turn);
        aps.getLeaf("Gr04").revealCreatures(cnl);
        aps.getLeaf("Gr04").addCreature("Gargoyle");
        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        cnl.add("Cyclops");
        aps.getLeaf("Gr12").revealCreatures(cnl);
        aps.getLeaf("Gr12").addCreature("Behemoth");
        aps.printLeaves();
        assertTrue(ps.getLeaf("Gr04").allCertain());
        assertTrue(ps.getLeaf("Gr07").allCertain());
        assertTrue(ps.getLeaf("Gr08").allCertain());
        assertTrue(ps.getLeaf("Gr12").allCertain());
    }

    public void testPredictSplits8()
    {
        Log.debug("testPredictSplits8()");
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        ps = new PredictSplits("Gr", "Gr11", cnl);
        aps.add_ps(ps);

        turn = 1;
        cnl.clear();
        cnl.add("Titan");
        cnl.add("Angel");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Ogre");
        cnl.add("Ogre");
        aps.getLeaf("Gr11").revealCreatures(cnl);
        aps.getLeaf("Gr11").split(4, "Gr02", turn);
        cnl.clear();
        cnl.add("Titan");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur");
        aps.getLeaf("Gr11").revealCreatures(cnl);
        aps.getLeaf("Gr11").addCreature("Centaur");
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        aps.printLeaves();

        turn = 2;
        cnl.clear();
        cnl.add("Titan");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Warlock");
        cnl.clear();
        cnl.add("Centaur");
        aps.getLeaf("Gr11").revealCreatures(cnl);
        aps.getLeaf("Gr11").addCreature("Centaur");
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        aps.printLeaves();

        turn = 3;
        cnl.clear();
        cnl.add("Cyclops");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Cyclops");
        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        aps.getLeaf("Gr11").revealCreatures(cnl);
        aps.getLeaf("Gr11").addCreature("Lion");
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        aps.printLeaves();

        turn = 4;
        aps.getLeaf("Gr02").split(2, "Gr10", turn);
        aps.getLeaf("Gr11").split(3, "Gr03", turn);
        aps.getLeaf("Gr11").merge(ps.getLeaf("Gr03"), turn);
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertFalse(ps.getLeaf("Gr10").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        aps.printLeaves();

        turn = 5;
        aps.getLeaf("Gr11").split(3, "Gr12", turn);
        cnl.clear();
        cnl.add("Warlock");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Warlock");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        aps.getLeaf("Gr10").revealCreatures(cnl);
        aps.getLeaf("Gr10").addCreature("Cyclops");

        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertTrue(ps.getLeaf("Gr10").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        assertFalse(ps.getLeaf("Gr12").allCertain());
        aps.printLeaves();

        cnl.clear();
        cnl.add("Centaur");
        cnl.add("Centaur");
        cnl.add("Centaur");
        aps.getLeaf("Gr12").revealCreatures(cnl);
        aps.getLeaf("Gr12").addCreature("Warbear");
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertTrue(ps.getLeaf("Gr10").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        assertTrue(ps.getLeaf("Gr12").allCertain());
        aps.printLeaves();

        cnl.clear();
        cnl.add("Cyclops");
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        aps.getLeaf("Gr10").revealCreatures(cnl);
        aps.getLeaf("Gr10").removeCreature("Cyclops");
        cnl.clear();
        cnl.add("Gargoyle");
        cnl.add("Gargoyle");
        aps.getLeaf("Gr10").revealCreatures(cnl);
        aps.getLeaf("Gr10").addCreature("Cyclops");
        aps.getLeaf("Gr10").removeCreature("Cyclops");
        aps.getLeaf("Gr10").removeCreature("Gargoyle");
        aps.getLeaf("Gr10").removeCreature("Gargoyle");
        aps.printLeaves();
        assertFalse(ps.getLeaf("Gr02").allCertain());
        assertFalse(ps.getLeaf("Gr11").allCertain());
        assertTrue(ps.getLeaf("Gr12").allCertain());

        turn = 6;
        cnl.clear();
        cnl.add("Centaur");
        aps.getLeaf("Gr02").revealCreatures(cnl);
        aps.getLeaf("Gr02").addCreature("Centaur");
        aps.printLeaves();
        assertTrue(ps.getLeaf("Gr02").allCertain());
        assertTrue(ps.getLeaf("Gr11").allCertain());
        assertTrue(ps.getLeaf("Gr12").allCertain());
    }
}


class AllPredictSplits
{
    private List pslist = new ArrayList();

    void add_ps(PredictSplits ps)
    {
        pslist.add(ps);
    }

    Node getLeaf(String markerId)
    {
        Iterator it = pslist.iterator();
        while (it.hasNext())
        {
            PredictSplits ps = (PredictSplits)it.next();
            Node leaf = ps.getLeaf(markerId);
            if (leaf != null)
            {
                return leaf;
            }
        }
        return null;
    }

    void printLeaves()
    {
        Iterator it = pslist.iterator();
        while (it.hasNext())
        {
            PredictSplits ps = (PredictSplits)it.next();
            ps.printLeaves();
        }
    }

    void printNodes()
    {
        Iterator it = pslist.iterator();
        while (it.hasNext())
        {
            PredictSplits ps = (PredictSplits)it.next();
            ps.printNodes();
        }
    }
}
