# $Header$

DVIPS=dvips
DVI2TTY=dvi2tty
LATEX2HTML=latex2html

DESTS=$(addsuffix .ps,$(SOURCES))
DESTSTXT=$(addsuffix .txt,$(SOURCES))
DESTSHTML=$(addsuffix .html,$(SOURCES))

all: $(DESTS) $(DESTSTXT) all-recursive

clean: clean-recursive
	rm -f *.aux *.log *.toc *.blg *.bbl *.dvi *~

distclean: clean distclean-recursive
	rm -f $(DESTS) $(DESTSTXT)

html: all $(DESTSHTML) html-recursive


htmlclean: distclean htmlclean-recursive
	rm -rf $(basename $(DESTSHTML))

# recursion in recursive
all-recursive html-recursive clean-recursive distclean-recursive htmlclean-recursive:
ifdef SUBDIR
	target=`echo $@ | sed 's/-recursive//g'`; \
	for subdir in $(SUBDIR); do cd $$subdir && $(MAKE) $$target; done
endif

## actual work below
%.ps: %.dvi
	$(DVIPS) $< -o $@

# three passes should make all the references OK
%.dvi: %.tex
	$(MAKEDVI) $(basename $<)

%.txt: %.dvi
	$(DVI2TTY) $< -o $@

%.html: %.tex
	$(LATEX2HTML) $<
