# $Header$

MAKEDVI=../buildtools/makedvi.sh

SOURCES=Base FileFormat CodingStandards FAQ build Credits README Variant-HOWTO HW-SW-Req network MarkerSet-HOWTO
SUBDIR=datatools

include Makefile.rules
