# $Header$

DVIPS=dvips
DVI2TTY=dvi2tty
LATEX2HTML=latex2html

## actual work below
%.ps: %.dvi
	$(DVIPS) $< -o $@

# three passes should make all the references OK
%.dvi: %.tex
	$(MAKEDVI) $(basename $<)

%.txt: %.dvi
	$(DVI2TTY) $< -o $@

%.html: %.tex
	$(LATEX2HTML) $<
