/* Generated By:JavaCC: Do not edit this line. BattlelandLoaderConstants.java */
package net.sf.colossus.parser;

public interface BattlelandLoaderConstants {

  int EOF = 0;
  int EOL = 4;
  int NUMBER = 5;
  int DIGIT = 6;
  int TERRAIN = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGIT>",
    "<TERRAIN>",
  };

}
