/* Generated By:JavaCC: Do not edit this line. CreatureLoaderConstants.java */
package net.sf.colossus.parser;

public interface CreatureLoaderConstants {

  int EOF = 0;
  int EOL = 4;
  int NUMBER = 5;
  int DIGIT = 6;
  int BOOL = 7;
  int CHAINE = 8;
  int CAR = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGIT>",
    "<BOOL>",
    "<CHAINE>",
    "<CAR>",
  };

}
